build:
        zig build

test:
        zig build test

clean:
        rm -f *.erl
        rm -f *.beam
        rm -f *.tl

install: build
        sudo cp zig-out/bin/tele /usr/local/bin/telec        
