build:
        zig build

test:
        zig build test

clean:
        rm -f *.erl
        rm -f *.beam
        rm -f *.tl       

release:
        zig build -Doptimize=ReleaseSmall --summary all

install: release
        sudo cp zig-out/bin/tele /usr/local/bin/telec
